<?php

namespace CULabs\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MensajeMasivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MensajeMasivoRepository extends EntityRepository
{
}
